# this is for when you want to run all test cases
name: End to end
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
      
        # this is for when you have a single script
      - name: My reports 
        # if always means if the first test fails it still moves on to the next
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: HTML Report
          path: cypress/reports/html # or path/to/artifact