name: Parallel scripts
on: push

jobs:
  add-To-Cart-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          command: npm run addToCart
          browser: firefox

  register-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          command: npm run registerFlow
          browser: firefox